[package]
name = "acorn"
version = "0.1.0"
edition = "2021"
default-run = "debug"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
indoc = "1.0.8"
nohash-hasher = "0.2.0"

[profile.release]
debug = true
